name: up_income
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_asset_generator: ^1.0.2
  flutter_dotenv: ^5.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  http: ^0.13.4
  intl_phone_number_input: ^0.7.0+2
  logger: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/gif/
    - assets/anim/
    - .env.dev
    - .env
